name: checkme
description: "A Todo List Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Riverpod for state management
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.3
  email_validator: ^2.1.17

  # SQLite database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.3 # Add this line
  path_provider: ^2.1.1
  path: ^1.8.3

  # Local Notifications
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4


  # (Optional) UUID generator for your Todo IDs
  uuid: ^4.4.0

  # Cupertino icons
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_avatar.png

